- hosts: localhost
  vars:
    squid_org_conf: /etc/squid/squid.conf
    squid_auth_conf: /home/ec2-user/ansible/template/squid.conf
  
  become: yes
  
  tasks:
    - name: install the latest version of Squid
      yum:
        name: squid
        state: latest
    - name: replase squid conf with user authentication based config
      template: 
        src=./template/squid.conf
        dest=/etc/squid/squid.conf
        owner: root
        group: squid
        mode: 0640

  handlers:
    - name: enable service squid
      service:
        name: squid
        enabled: yes
    - name: start service squid
      service:
        name: squid
        state: started
