- hosts: localhost
  
  become: yes
  
  tasks:
    - name: install the latest version of Squid
      yum:
        name: squid
        state: latest
    
    - name: replase squid conf with user authentication based config
      template: 
        src: /home/ec2-user/ansible/template/squid.conf
        dest: /etc/squid/squid.conf
        owner: root
        group: squid
        mode: 0640

    - name: set user authentication file
      copy:
        src: /home/ec2-user/ansible/template/.users
        dest: /etc/squid/.users

    - name: enable squid
      service:
        name: squid
        enabled: yes
        
    - name: start squid
      service:
        name: squid
        state: started


  handlers:
    - name: enable service squid
      service:
        name: squid
        enabled: yes
    - name: start service squid
      service:
        name: squid
        state: started
